name: React Chat-app

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build app for github pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secret.GITHUB_TOKEN }}
          publish_dir: dist

      # Optional: run tests if you have them
      # - name: Run tests
      #   run: npm run test
